# Generated by Django 4.0 on 2021-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('discord_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='discord_id')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='email')),
                ('cny', models.IntegerField(default=0, verbose_name='Yuan')),
                ('rub', models.IntegerField(default=0, verbose_name='Rubel')),
                ('lir', models.IntegerField(default=0, verbose_name='Lira')),
                ('clp', models.IntegerField(default=0, verbose_name='Peso chilijskie')),
                ('tp', models.IntegerField(default=0, verbose_name='Peso tarpijskie')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
