# Generated by Django 4.0 on 2021-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='discord_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='discord_id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='email'),
        ),
    ]
