version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/django-bank
    ports:
      - 8000:8000
    image: app:django-bank
    container_name: django_bank_container
    command: python3 manage.py runserver 0.0.0.0:8000