version: "3.9"
services:
  bank:
    build: .
    volumes:
      - .:/django-bank
    ports:
      - 8000:8000
    image: app:django-bank
    container_name: django_bank_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - pgdb:/var/lib/postresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db_container

volumes:
  pgdb: