# Generated by Django 4.0 on 2022-01-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_discord_id_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_from', models.CharField(choices=[('CNY', 'Yuan'), ('RUB', 'Rubel'), ('LIR', 'Lira'), ('CLP', 'Peso chilijskie')], max_length=32, verbose_name='Wymiana z')),
                ('exchange_to', models.CharField(choices=[('CNY', 'Yuan'), ('RUB', 'Rubel'), ('LIR', 'Lira'), ('CLP', 'Peso chilijskie')], max_length=32, verbose_name='Wymiana na')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Kwota')),
                ('ratio', models.FloatField(default=1, verbose_name='Ratio')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
