# Generated by Django 4.0 on 2022-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangelisting',
            name='ratio',
        ),
        migrations.AddField(
            model_name='exchangelisting',
            name='rati_to',
            field=models.PositiveIntegerField(default=1, verbose_name='Ratio Dół'),
        ),
        migrations.AddField(
            model_name='exchangelisting',
            name='ratio_from',
            field=models.PositiveIntegerField(default=1, verbose_name='Ratio Góra'),
        ),
    ]
