# Generated by Django 4.0 on 2021-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Tranzakcji')),
                ('sender_id', models.PositiveIntegerField(verbose_name='Id Nadawcy')),
                ('reciver_id', models.PositiveIntegerField(verbose_name='Id odbiorcy')),
                ('kwota', models.PositiveIntegerField(default=0, verbose_name='Kwota')),
                ('waluta', models.CharField(max_length=32, verbose_name='Waluta')),
                ('data_transakcji', models.DateTimeField(auto_now_add=True, verbose_name='Data Transakcji')),
                ('typ', models.PositiveIntegerField(default=0, verbose_name='Typ transakcji')),
                ('title', models.CharField(default='Tytuł Przelewu', max_length=100, verbose_name='Tytuł przelewu')),
            ],
        ),
    ]
