# Generated by Django 4.0 on 2022-01-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_discord_id_alter_account_email'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='waluta',
            field=models.CharField(choices=[('CNY', 'Yuan'), ('RUB', 'Rubel'), ('LIR', 'Lira'), ('CLP', 'Peso chilijskie')], max_length=32, verbose_name='Waluta'),
        ),
    ]
