# Generated by Django 4.0 on 2022-01-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_discord_id_alter_account_email'),
        ('transactions', '0002_alter_transaction_sender_id_alter_transaction_waluta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reciver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciver_id', to='account.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_id', to='account.account'),
        ),
    ]
