# Generated by Django 4.0 on 2022-01-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('account', '0002_alter_account_discord_id_alter_account_email'),
        ('transactions', '0005_alter_transaction_reciver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reciver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Odbiorca', to='account.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nadawca', to='account.account'),
        ),
    ]
