# Generated by Django 4.0 on 2022-04-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_discord_id_alter_account_email'),
        ('transactions', '0006_alter_transaction_reciver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reciver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Odbiorca', to='account.account', verbose_name='Odbiorca'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nadawca', to='account.account', verbose_name='Nadawca'),
        ),
    ]
