# Generated by Django 4.0.4 on 2022-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionorder',
            name='transaction_delay',
            field=models.IntegerField(choices=[(1, 'Codziennie'), (7, 'Co siedem dni'), (30, 'Raz na 30 dni'), (90, 'Raz na 90 dni'), (365, 'Raz na 365 dni')], verbose_name='Cykliczność'),
        ),
    ]
